INFO       09:13:50 root                           __init__                             29  : Connected to MinIO server
INFO       09:13:50 root                           create_bucket                        18  : Creating bucket cifar-10-5-chunks
INFO       09:13:50 root                           create_bucket                        24  : Created bucket cifar-10-5-chunks
INFO       09:13:53 asynfed.server.server          __init__                             116 : Queue ready!
INFO       09:13:53 asynfed.server.server          __init__                             118 : 

Server Info:
	Queue In : {'exchange_name': 'asynfl_exchange', 'exchange_type': 'topic', 'queue_name': 'server_consumer', 'routing_key': 'server.#', 'end_point': 'amqps://gocktdwu:jYQBoATqKHRqXaV4O9TahpPcbd8xjcaw@armadillo.rmq.cloudamqp.com/gocktdwu'}
	Queue Out : {'exchange_name': 'asynfl_exchange', 'exchange_type': 'topic', 'queue_name': 'server_queue', 'routing_key': 'client.#', 'end_point': 'amqps://gocktdwu:jYQBoATqKHRqXaV4O9TahpPcbd8xjcaw@armadillo.rmq.cloudamqp.com/gocktdwu'}
	S3 Bucket: cifar-10-5-chunks


INFO       09:13:53 asynfed.server.server          start                                139 : No local update found, sleep for 30 seconds...
INFO       09:14:23 asynfed.server.server          start                                139 : No local update found, sleep for 30 seconds...
--- Logging error ---
Traceback (most recent call last):
  File "/home/student02/anaconda3/envs/tensorflow-cpu/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/home/student02/anaconda3/envs/tensorflow-cpu/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/home/student02/anaconda3/envs/tensorflow-cpu/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/home/student02/anaconda3/envs/tensorflow-cpu/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/student02/anaconda3/envs/tensorflow-cpu/lib/python3.9/threading.py", line 937, in _bootstrap
    self._bootstrap_inner()
  File "/home/student02/anaconda3/envs/tensorflow-cpu/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/student02/anaconda3/envs/tensorflow-cpu/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/student02/nguyen_vuong/AsynFL/asynfed/server/server.py", line 244, in _clean_cloud_storage
    LOGGER.info(current_version, threshold)
Message: 18
Arguments: (13,)
--- Logging error ---
Traceback (most recent call last):
  File "/home/student02/anaconda3/envs/tensorflow-cpu/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/home/student02/anaconda3/envs/tensorflow-cpu/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/home/student02/anaconda3/envs/tensorflow-cpu/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/home/student02/anaconda3/envs/tensorflow-cpu/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/student02/anaconda3/envs/tensorflow-cpu/lib/python3.9/threading.py", line 937, in _bootstrap
    self._bootstrap_inner()
  File "/home/student02/anaconda3/envs/tensorflow-cpu/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/student02/anaconda3/envs/tensorflow-cpu/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/student02/nguyen_vuong/AsynFL/asynfed/server/server.py", line 256, in _clean_cloud_storage
    LOGGER.info(w_id, worker.newest_used_version, threshold)
Message: '235-cpu'
Arguments: (12, 7)
--- Logging error ---
Traceback (most recent call last):
  File "/home/student02/anaconda3/envs/tensorflow-cpu/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/home/student02/anaconda3/envs/tensorflow-cpu/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/home/student02/anaconda3/envs/tensorflow-cpu/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/home/student02/anaconda3/envs/tensorflow-cpu/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/student02/anaconda3/envs/tensorflow-cpu/lib/python3.9/threading.py", line 937, in _bootstrap
    self._bootstrap_inner()
  File "/home/student02/anaconda3/envs/tensorflow-cpu/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/student02/anaconda3/envs/tensorflow-cpu/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/student02/nguyen_vuong/AsynFL/asynfed/server/server.py", line 256, in _clean_cloud_storage
    LOGGER.info(w_id, worker.newest_used_version, threshold)
Message: 'local-client'
Arguments: (14, 9)
